### ISSUE TITLE
dev: Fix all mypy errors

### ISSUE THREAD

**Issue by akhercha** [astraly-labs/pragma-sdk#116]
### Feature Request

We currently have a lot of `mypy` types errors currently (~700).

Instead of fixing them all in one go, we decided to disable them for now, see `pyproject.toml`:
```toml
[tool.mypy]
files = ["pragma"]
namespace_packages = true
explicit_package_bases = true
show_error_codes = true
strict = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
# TODO: Stop ignoring the folders one by one & fix the mypy errors
exclude = [
  "pragma/tests/.*",
  "pragma-oracle",
  "stagecoach",
  "pragma/core",
  "pragma/publisher",
  "pragma/tests",
]
```

We should remove those two folders from the ignored folders:
```
"pragma/core",
"pragma/publisher",
```
and fix the associated errors that will pop upon doing `mypy .` or `poe typecheck`.
